language: python
services:
  - mysql
python:
  - "3.6"

# command to install dependencies
install:
  - pip install .[testing]
  - platiagro-init-db

# command to run tests
script:
  - pytest --cov=projects --cov-report=xml

after_script:
  - codecov

notifications:
  email: false
