version: '3'

services:
  app:
    container_name: projects
    image: node:lts-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command: npm run start

  db:
    build: ./database-service
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
