version: '3'

services:
  app:
    container_name: projects
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
      - minio
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command: ["-c", "npm install && /opt/wait-for.sh ${DB_HOST:-mysql}:${DB_PORT:-3306} && knex migrate:latest && npm run start-dev"]
    entrypoint: ["/bin/sh"]

  db:
    container_name: '${DB_HOST:-mysql}'
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-projects}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      
  minio:
    container_name: '${MINIO_HOST:-minio-service}'
    image: minio/minio
    volumes:
      - ./data-minio:/var/lib/minio
    ports:
      - '${MINIO_PORT:-9000}:9000'
    environment:
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY:-minio}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY:-minio123}'
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://minio:9000/minio/health/live']
      interval: 1m30s
      timeout: 20s
      retries: 3
